/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 model.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import {motion} from "framer-motion-3d"

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <motion.group {...props} dispose={null}
    initial={{
      scale: 0
    }}
    animate={{
      scale: 1,
      transition: { duration: 1.5, delay: 1.2}
    }}
    >
      
      <motion.mesh
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 1, delay: 1.5}
      }}
      geometry={nodes.Cube001.geometry} material={materials.glow} position={[1.451, 3.2, 0.019]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 1, delay: 1.5}
      }}
      geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[1.826, 4.097, 0.002]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 1, delay: 1.5}
      }}
      geometry={nodes.Cylinder.geometry} material={materials.darkblue} position={[-1.178, 1.626, -3.337]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 1, delay: 1.5}
      }}
      geometry={nodes.Cube003.geometry} material={materials.darkblue} position={[-1.786, 1.653, 3.525]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 1, delay: 1.5}
      }}
      geometry={nodes.Plane.geometry} material={materials.glow} position={[-2.831, 1.432, -0.312]} />
      <motion.group
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 1.8}
      }}
      position={[0.817, 1.64, 4.206]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.darkblue} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.010']} />
      </motion.group>
      <mesh geometry={nodes.NurbsPath.geometry} material={materials['Material.001']} position={[2.3, 1.393, 2.503]} />
      <motion.group
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2}
      }}
      position={[2.269, 0.582, 0.371]}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials.glow} />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials.darkblue} />
      </motion.group>
      <motion.group
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2}
      }}
      position={[2.073, 0.689, -3.415]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.logo} />
      </motion.group>
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube008.geometry} material={materials.darkblue} position={[2.049, 0.689, -4.601]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.NurbsPath001.geometry} material={materials.glow} position={[2.894, 1.039, 2.48]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cylinder008.geometry} material={materials['Material.001']} position={[-0.093, 0.31, 0.629]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cylinder009.geometry} material={materials.darkblue} position={[-0.104, 0.873, 0.612]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cylinder010.geometry} material={materials.metal} position={[-0.749, 2.695, -5.222]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube011.geometry} material={materials['01 - Defaultg']} position={[-0.473, 1.251, -5.158]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cylinder011.geometry} material={materials.metal} position={[-0.213, 2.529, -5.222]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cylinder012.geometry} material={materials.metal} position={[-0.213, 0.241, -5.222]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cylinder013.geometry} material={materials.metal} position={[-0.807, 0.242, -5.222]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube009.geometry} material={materials['Material.001']} position={[-2.107, 0.589, -2.755]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Plane001.geometry} material={materials.darkblue} position={[-2.08, 2.225, -5.267]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube015.geometry} material={materials.darkblue} position={[-3.165, 1.649, -0.001]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cylinder017.geometry} material={materials.glow} position={[-0.092, 0.255, 0.631]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube018.geometry} material={materials['Material.010']} position={[-0.473, 1.251, -5.285]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube019.geometry} material={materials.darkblue} position={[-0.509, 1.269, -5.224]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Plane003.geometry} material={materials['Material.001']} position={[1.543, 2.398, 0.584]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[-2.755, 1.459, -0.358]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Text.geometry} material={materials.darkblue} position={[1.759, 4.086, -1.483]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube020.geometry} material={materials.darkblue} position={[-0.368, 1.653, 4.152]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube021.geometry} material={materials.darkblue} position={[-2.071, 1.079, 2.065]} />
      <motion.mesh 
      initial={{
        scale: 0,
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.5, delay: 2.5}
      }}
      geometry={nodes.Cube022.geometry} material={materials.darkblue} />
      <motion.group
      initial={{
        scale: 0
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.8, delay: 2.8}
      }}
      position={[1.724, 1.03, -3.702]}>
        <mesh geometry={nodes.Wolf3D_Body003.geometry} material={materials['Wolf3D_Body.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_1.geometry} material={materials['Wolf3D_Eye.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_2.geometry} material={materials['Wolf3D_Skin.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_3.geometry} material={materials['Wolf3D_Teeth.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_4.geometry} material={materials.M_Hair_60} />
        <mesh geometry={nodes.Wolf3D_Body003_5.geometry} material={materials['Wolf3D_Outfit_Bottom.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_6.geometry} material={materials['Wolf3D_Outfit_Footwear.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_7.geometry} material={materials['Wolf3D_Outfit_Top.009']} />
      </motion.group>
      <mesh geometry={nodes.thirdChair.geometry} material={materials.wood} position={[1.688, 0.545, -3.704]} />
      <mesh geometry={nodes.thirdChair001.geometry} material={materials['Material.014']} position={[1.673, 0.842, -3.704]} />
      <mesh geometry={nodes.eb_house_plant_02.geometry} material={materials['blinn1SG.001']} position={[2.275, 1.191, -0.218]} />
      <motion.group
      initial={{
        scale: 0
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.8, delay: 2.8}
      }}
      position={[-0.007, 0.616, -2.677]}>
        <mesh geometry={nodes.Line342918_1.geometry} material={materials.sfa} />
        <mesh geometry={nodes.Line342918_2.geometry} material={materials['Material #51']} />
        <mesh geometry={nodes.Line342918_3.geometry} material={materials['01 - Defaultg']} />
        <mesh geometry={nodes.Line342918_4.geometry} material={materials['Material #84']} />
        <mesh geometry={nodes.Line342918_5.geometry} material={materials['01 - Defaultd']} />
      </motion.group>
      <motion.group
      initial={{
        scale: 0
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.8, delay: 2.8}
      }}
      position={[-1.939, 0.648, 0.477]}>
        <mesh geometry={nodes.Line342918001_1.geometry} material={materials.sfa} />
        <mesh geometry={nodes.Line342918001_2.geometry} material={materials['Material #51']} />
        <mesh geometry={nodes.Line342918001_3.geometry} material={materials['01 - Defaultg']} />
        <mesh geometry={nodes.Line342918001_4.geometry} material={materials['Material #84']} />
        <mesh geometry={nodes.Line342918001_5.geometry} material={materials['01 - Defaultd']} />
      </motion.group>
      <motion.group
      initial={{
        scale: 0
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.8, delay: 2.8}
      }}
      position={[2.36, 1.406, 3.996]} rotation={[-Math.PI, 0.065, -Math.PI]}>
        <mesh geometry={nodes.Archmodels70_032_02_1.geometry} material={materials.Archmodels70_032_02} />
        <mesh geometry={nodes.Archmodels70_032_02_2.geometry} material={materials['Material #2097631719']} />
        <mesh geometry={nodes.Archmodels70_032_02_3.geometry} material={materials['Material #2097631714']} />
        <mesh geometry={nodes.Archmodels70_032_02_4.geometry} material={materials.Archmodels70_032_04} />
        <mesh geometry={nodes.Archmodels70_032_02_5.geometry} material={materials.Archmodels70_032_05} />
        <mesh geometry={nodes.Archmodels70_032_02_6.geometry} material={materials['Material #2097631711']} />
        <mesh geometry={nodes.Archmodels70_032_02_7.geometry} material={materials['Material #2097631715']} />
        <mesh geometry={nodes.Archmodels70_032_02_8.geometry} material={materials['Material #2097631716']} />
        <mesh geometry={nodes.Archmodels70_032_02_9.geometry} material={materials['Material #2097631717']} />
        <mesh geometry={nodes.Archmodels70_032_02_10.geometry} material={materials['Material #2097631712']} />
        <mesh geometry={nodes.Archmodels70_032_02_11.geometry} material={materials.Archmodels70_032_11} />
      </motion.group>
      <motion.group
      initial={{
        scale: 0
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.8, delay: 2.8}
      }}
      position={[0.768, 0.88, 0.177]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube016_3.geometry} material={materials['Material.002']} />
      </motion.group>
      <motion.group
      initial={{
        scale: 0
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.8, delay: 2.8}
      }}
      position={[0.634, 0.886, 0.048]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube019_3.geometry} material={materials['Material.006']} />
      </motion.group>
      <motion.group
      initial={{
        scale: 0
      }}
      animate={{
        scale: 1,
        transition: { duration: 0.8, delay: 2.8}
      }}
      position={[0.57, 0.89, -0.084]}>
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube028_3.geometry} material={materials['Material.006']} />
      </motion.group>




      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cube013.geometry} material={materials.glow} position={[1.447, 0.09, 0.018]} scale={[1.009, 1, 1.008]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cube024.geometry} material={materials['Material.004']} position={[-1.644, 1.656, 4.975]} scale={[1.037, 1, 1]} />
      <group position={[0.825, 0.643, 5.297]} rotation={[0, -1.571, 0]} scale={[0.696, 1, 1]}>
        <motion.mesh
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{duration: 1, delay: 3}}
        geometry={nodes.Cube031.geometry} material={materials['Material.001']} />
        <motion.mesh
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{duration: 1, delay: 3}}
        geometry={nodes.Cube031_1.geometry} material={materials.glow} />
        <motion.mesh
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{duration: 1, delay: 3}}
        geometry={nodes.Cube031_2.geometry} material={materials.darkblue} />
      </group>
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cube012.geometry} material={materials.darkblue} position={[-1.004, 3.988, -4.969]} scale={[0.817, 0.917, 0.127]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[-1.66, 0.406, 5.118]} scale={[1.502, 0.244, 0.135]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[0.539, 0.199, 3.131]} scale={[0.8, 0.072, 0.694]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cube017.geometry} material={materials['Material.012']} position={[0.539, 0.592, 2.459]} scale={[0.8, 0.072, 0.694]} />
      <group position={[0.267, 0.588, 2.414]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.244, 0.141, 0.244]}>
        <motion.mesh
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{duration: 1, delay: 3}}
        geometry={nodes.Text005.geometry} material={materials.Material} />
        <motion.mesh
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{duration: 1, delay: 3}}
        geometry={nodes.Text005_1.geometry} material={materials.darkblue} />
      </group>
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cube027.geometry} material={materials.glow} position={[0.539, 0.2, 3.123]} scale={[0.8, 0.072, 0.694]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.NurbsPath002.geometry} material={materials.Archmodels70_032_11} position={[1.905, 5.007, -4.362]} rotation={[0, 0, 0.4]} scale={0.781} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[2.569, 5.08, -4.354]} rotation={[-Math.PI, 0, -2.52]} scale={[-0.125, -0.429, -0.136]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.NurbsPath003.geometry} material={materials.Archmodels70_032_11} position={[1.953, 5.007, -2.212]} rotation={[0, 0, 0.4]} scale={0.781} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[2.535, 5.08, -2.189]} rotation={[-Math.PI, 0, -2.52]} scale={[-0.125, -0.429, -0.136]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.NurbsPath004.geometry} material={materials.Archmodels70_032_11} position={[1.945, 5.007, 0.15]} rotation={[0, 0, 0.4]} scale={0.781} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cylinder003.geometry} material={materials.Material} position={[2.527, 5.08, 0.185]} rotation={[-Math.PI, 0, -2.52]} scale={[-0.125, -0.429, -0.136]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.NurbsPath005.geometry} material={materials.Archmodels70_032_11} position={[2.309, 5.007, 2.191]} rotation={[0, 0.051, 0.4]} scale={0.781} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[3.023, 5.08, 2.158]} rotation={[-Math.PI, -0.051, -2.52]} scale={[-0.125, -0.429, -0.136]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[-1.66, 0.406, 5.118]} scale={[1.502, 0.244, 0.135]} />
      <motion.mesh
      initial={{opacity: 0}}
      animate={{opacity: 1}}
      transition={{duration: 1, delay: 3}}
      geometry={nodes.Plane007.geometry} material={materials['5eewe']} position={[-2.819, 0.707, 5.116]} scale={[0.967, 1.122, 0.79]} />
      <group position={[0.86, 0.884, 0.498]}>
        <motion.mesh
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{duration: 1, delay: 3}}
        geometry={nodes.Object_0.geometry} material={materials['Material.008']} />
        <motion.mesh
        initial={{opacity: 0}}
        animate={{opacity: 1}}
        transition={{duration: 1, delay: 3}}
        geometry={nodes.Object_0_1.geometry} material={materials['Material.009']} />
      </group>
    </motion.group>
  )
}

useGLTF.preload('/model.glb')
