/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 newModel.glb 
*/
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 newModel.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/newModel.glb')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={true} far={1000} near={0.1} fov={22.895} position={[17.783, 6.429, 16.447]} rotation={[-0.275, 0.829, 0.205]} />
      <pointLight intensity={30} decay={2} position={[-2.409, 7.308, 3.435]} rotation={[-1.069, -0.386, -0.602]} />
      <pointLight intensity={30} decay={2} position={[9.583, 2.244, 0.193]} rotation={[-1.747, 1.431, 1.749]} />
      <pointLight intensity={30} decay={2} position={[1.032, 5.365, 8.015]} rotation={[-0.559, 0.322, 0.196]} />
      <pointLight intensity={30} decay={2} position={[-0.23, 2.91, -8.745]} rotation={[-2.901, 0.178, 3.098]} />
      <pointLight intensity={30} decay={2} position={[0.122, 1.353, 0.368]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={30} decay={2} position={[1.549, 1.65, 2.836]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={30} decay={2} position={[0.944, 2.054, -2.581]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={30} decay={2} position={[-0.988, 1.513, 6.366]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={30} decay={2} position={[2.445, 4.889, -4.327]} rotation={[1.518, 1.334, -1.516]} />
      <pointLight intensity={30} decay={2} position={[2.445, 4.889, -2.747]} rotation={[1.828, 1.327, -1.836]} />
      <pointLight intensity={30} decay={2} position={[2.445, 4.889, -0.884]} rotation={[1.8, 1.328, -1.807]} />
      <pointLight intensity={30} decay={2} position={[2.447, 4.828, 0.736]} rotation={[1.704, 1.223, -1.712]} />
      <pointLight intensity={30} decay={2} position={[4.491, 5.323, -1.652]} rotation={[-1.998, 0.897, 2.099]} />
      <pointLight intensity={30} decay={2} position={[1.12, 5.131, -8.608]} rotation={[-2.683, 0.293, 3]} />
      <pointLight intensity={30} decay={2} position={[-7.953, 2.244, 0.193]} rotation={[-1.747, -1.307, -1.753]} />
      <pointLight intensity={30} decay={2} position={[-7.953, 2.244, -5.965]} rotation={[-2.899, -0.736, -2.977]} />
      <pointLight intensity={30} decay={2} position={[-7.953, 2.244, 7.081]} rotation={[-0.237, -0.725, -0.89]} />
      <pointLight intensity={30} decay={2} position={[0.352, -3.607, -0.003]} rotation={[1.683, 0.491, -1.805]} />
      <pointLight intensity={30} decay={2} position={[-2.409, 7.308, -1.597]} rotation={[-1.802, -0.424, -2.091]} />
      <pointLight intensity={30} decay={2} position={[-3.619, 2.244, 9.537]} rotation={[-0.174, -0.181, -0.032]} />
     
      <mesh geometry={nodes.Cube001.geometry} material={materials.glow} position={[1.451, 3.2, 0.019]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[1.826, 4.097, 0.002]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.darkblue} position={[-1.178, 1.626, -3.337]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.darkblue} position={[-1.786, 1.653, 3.525]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.glow} position={[-2.831, 1.432, -0.312]} />
      <group position={[0.817, 1.64, 4.206]}>
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.darkblue} />
        <mesh geometry={nodes.Cube006_3.geometry} material={materials['Material.010']} />
      </group>
      <mesh geometry={nodes.NurbsPath.geometry} material={materials['Material.001']} position={[2.3, 1.393, 2.503]} />
      <group position={[2.269, 0.582, 0.371]}>
        <mesh geometry={nodes.Cube007_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube007_2.geometry} material={materials.glow} />
        <mesh geometry={nodes.Cube007_3.geometry} material={materials.darkblue} />
      </group>
      <group position={[2.073, 0.689, -3.415]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.logo} />
      </group>
      <mesh geometry={nodes.Cube008.geometry} material={materials.darkblue} position={[2.049, 0.689, -4.601]} />
      <mesh geometry={nodes.NurbsPath001.geometry} material={materials.glow} position={[2.894, 1.039, 2.48]} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials['Material.001']} position={[-0.093, 0.31, 0.629]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.darkblue} position={[-0.104, 0.873, 0.612]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.metal} position={[-0.749, 2.695, -5.222]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['01 - Defaultg']} position={[-0.473, 1.251, -5.158]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.metal} position={[-0.213, 2.529, -5.222]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.metal} position={[-0.213, 0.241, -5.222]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.metal} position={[-0.807, 0.242, -5.222]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials['Material.001']} position={[-2.107, 0.589, -2.755]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.darkblue} position={[-2.08, 2.225, -5.267]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.darkblue} position={[-3.165, 1.649, -0.001]} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials.glow} position={[-0.092, 0.255, 0.631]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.010']} position={[-0.473, 1.251, -5.285]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials.darkblue} position={[-0.509, 1.269, -5.224]} />
      <group position={[1.543, 2.398, 0.584]}>
        <mesh geometry={nodes.main.geometry} material={materials.darkblue} />
        <mesh geometry={nodes.main_1.geometry} material={materials['Material.001']} />
      </group>
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.004']} position={[-2.755, 1.459, -0.358]} />
      <mesh geometry={nodes.Text.geometry} material={materials.darkblue} position={[1.759, 4.086, -1.483]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.darkblue} position={[-0.368, 1.653, 4.152]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials.darkblue} position={[-2.071, 1.079, 2.065]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.darkblue} />
      <group position={[1.724, 1.03, -3.702]}>
        <mesh geometry={nodes.Wolf3D_Body003.geometry} material={materials['Wolf3D_Body.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_1.geometry} material={materials['Wolf3D_Eye.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_2.geometry} material={materials['Wolf3D_Skin.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_3.geometry} material={materials['Wolf3D_Teeth.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_4.geometry} material={materials.M_Hair_60} />
        <mesh geometry={nodes.Wolf3D_Body003_5.geometry} material={materials['Wolf3D_Outfit_Bottom.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_6.geometry} material={materials['Wolf3D_Outfit_Footwear.009']} />
        <mesh geometry={nodes.Wolf3D_Body003_7.geometry} material={materials['Wolf3D_Outfit_Top.009']} />
      </group>
      <mesh geometry={nodes.thirdChair.geometry} material={materials.wood} position={[1.688, 0.545, -3.704]} />
      <mesh geometry={nodes.thirdChair001.geometry} material={materials['Material.014']} position={[1.673, 0.842, -3.704]} />
      <mesh geometry={nodes.eb_house_plant_02.geometry} material={materials['blinn1SG.001']} position={[2.275, 1.191, -0.218]} />
      <group position={[-0.007, 0.616, -2.677]}>
        <mesh geometry={nodes.Line342918_1.geometry} material={materials.sfa} />
        <mesh geometry={nodes.Line342918_2.geometry} material={materials['Material #51']} />
        <mesh geometry={nodes.Line342918_3.geometry} material={materials['01 - Defaultg']} />
        <mesh geometry={nodes.Line342918_4.geometry} material={materials['Material #84']} />
        <mesh geometry={nodes.Line342918_5.geometry} material={materials['01 - Defaultd']} />
      </group>
      <group position={[-1.939, 0.648, 0.477]}>
        <mesh geometry={nodes.Line342918001_1.geometry} material={materials.sfa} />
        <mesh geometry={nodes.Line342918001_2.geometry} material={materials['Material #51']} />
        <mesh geometry={nodes.Line342918001_3.geometry} material={materials['01 - Defaultg']} />
        <mesh geometry={nodes.Line342918001_4.geometry} material={materials['Material #84']} />
        <mesh geometry={nodes.Line342918001_5.geometry} material={materials['01 - Defaultd']} />
      </group>
      <group position={[2.36, 1.406, 3.996]} rotation={[-Math.PI, 0.065, -Math.PI]}>
        <mesh geometry={nodes.Archmodels70_032_02_1.geometry} material={materials.Archmodels70_032_02} />
        <mesh geometry={nodes.Archmodels70_032_02_2.geometry} material={materials['Material #2097631719']} />
        <mesh geometry={nodes.Archmodels70_032_02_3.geometry} material={materials['Material #2097631714']} />
        <mesh geometry={nodes.Archmodels70_032_02_4.geometry} material={materials.Archmodels70_032_04} />
        <mesh geometry={nodes.Archmodels70_032_02_5.geometry} material={materials.Archmodels70_032_05} />
        <mesh geometry={nodes.Archmodels70_032_02_6.geometry} material={materials['Material #2097631711']} />
        <mesh geometry={nodes.Archmodels70_032_02_7.geometry} material={materials['Material #2097631715']} />
        <mesh geometry={nodes.Archmodels70_032_02_8.geometry} material={materials['Material #2097631716']} />
        <mesh geometry={nodes.Archmodels70_032_02_9.geometry} material={materials['Material #2097631717']} />
        <mesh geometry={nodes.Archmodels70_032_02_10.geometry} material={materials['Material #2097631712']} />
        <mesh geometry={nodes.Archmodels70_032_02_11.geometry} material={materials.Archmodels70_032_11} />
      </group>
      <group position={[0.768, 0.88, 0.177]}>
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube016_3.geometry} material={materials['Material.002']} />
      </group>
      <group position={[0.634, 0.886, 0.048]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube019_3.geometry} material={materials['Material.006']} />
      </group>
      <group position={[0.57, 0.89, -0.084]}>
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.007']} />
        <mesh geometry={nodes.Cube028_2.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Cube028_3.geometry} material={materials['Material.006']} />
      </group>
      <mesh geometry={nodes.Cube013.geometry} material={materials.glow} position={[1.447, 0.09, 0.018]} scale={[1.009, 1, 1.008]} />
      <mesh geometry={nodes.Cube024.geometry} material={materials['Material.004']} position={[-1.644, 1.656, 4.975]} scale={[1.037, 1, 1]} />
      <group position={[0.825, 0.643, 5.297]} rotation={[0, -1.571, 0]} scale={[0.696, 1, 1]}>
        <mesh geometry={nodes.Cube031.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials.glow} />
        <mesh geometry={nodes.Cube031_2.geometry} material={materials.darkblue} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials.darkblue} position={[0.336, 3.546, 3.737]} scale={[0.817, 0.917, 0.127]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.darkblue} position={[-1.004, 3.988, -4.969]} scale={[0.817, 0.917, 0.127]} />
      <mesh geometry={nodes.Cube025.geometry} material={nodes.Cube025.material} position={[-1.66, 0.406, 5.118]} scale={[1.502, 0.244, 0.135]} />
      <mesh geometry={nodes.Cube016.geometry} material={nodes.Cube016.material} position={[0.539, 0.199, 3.131]} scale={[0.8, 0.072, 0.694]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.012']} position={[0.539, 0.592, 2.459]} scale={[0.8, 0.072, 0.694]} />
      <group position={[0.267, 0.588, 2.414]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[0.244, 0.141, 0.244]}>
        <mesh geometry={nodes.Text005.geometry} material={materials.Material} />
        <mesh geometry={nodes.Text005_1.geometry} material={materials.darkblue} />
      </group>
      <mesh geometry={nodes.Cube027.geometry} material={materials.glow} position={[0.539, 0.2, 3.123]} scale={[0.8, 0.072, 0.694]} />
      <mesh geometry={nodes.NurbsPath002.geometry} material={materials.Archmodels70_032_11} position={[1.958, 5.007, -4.334]} rotation={[0, 0, 0.4]} scale={0.781} />
      <mesh geometry={nodes.Cylinder001.geometry} material={nodes.Cylinder001.material} position={[2.54, 5.08, -4.361]} rotation={[-Math.PI, 0, -2.52]} scale={[-0.132, -0.452, -0.132]} />
      <mesh geometry={nodes.NurbsPath003.geometry} material={materials.Archmodels70_032_11} position={[1.958, 5.007, -2.716]} rotation={[0, 0, 0.4]} scale={0.781} />
      <mesh geometry={nodes.Cylinder002.geometry} material={nodes.Cylinder002.material} position={[2.54, 5.08, -2.744]} rotation={[-Math.PI, 0, -2.52]} scale={[-0.132, -0.452, -0.132]} />
      <mesh geometry={nodes.NurbsPath004.geometry} material={materials.Archmodels70_032_11} position={[1.958, 5.007, -0.857]} rotation={[0, 0, 0.4]} scale={0.781} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Material} position={[2.54, 5.08, -0.885]} rotation={[-Math.PI, 0, -2.52]} scale={[-0.132, -0.452, -0.132]} />
      <mesh geometry={nodes.NurbsPath005.geometry} material={materials.Archmodels70_032_11} position={[1.949, 5.007, 0.76]} rotation={[0, 0, 0.4]} scale={0.781} />
      <mesh geometry={nodes.Cylinder004.geometry} material={nodes.Cylinder004.material} position={[2.54, 5.08, 0.732]} rotation={[-Math.PI, 0, -2.52]} scale={[-0.132, -0.452, -0.132]} />
      <mesh geometry={nodes.Cube028.geometry} material={nodes.Cube028.material} position={[-1.66, 0.406, 5.118]} scale={[1.502, 0.244, 0.135]} />
      <mesh geometry={nodes.Plane007.geometry} material={materials['5eewe']} position={[-2.819, 0.707, 5.116]} scale={[0.967, 1.122, 0.79]} />
      <group position={[0.86, 0.884, 0.498]}>
        <mesh geometry={nodes.Object_0.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.Object_0_1.geometry} material={materials['Material.009']} />
      </group>
    </group>
  )
}

useGLTF.preload('/newModel.glb')
