import "./globals.css";
import {Main, Secondary, Mon} from "./../assets/fonts.js"


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Main.className} ${Secondary.variable} ${Mon.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
