/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 building.glb 
*/
import React, { useEffect, useRef, useState } from "react";
import { PerspectiveCamera, useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { useFrame } from "@react-three/fiber";


export function Model(props) {

  const groupRef = useRef();
  const [animate, setAnimate] = useState(false);
  useEffect(() => {
    setTimeout(() => {
      setAnimate(true);
    }, 6000);
    setTimeout(() => {
      setAnimate(false);
    }, 16500);
    
  }, [])
  useFrame(() => {
    if (animate === true) {
    groupRef.current.rotation.y += 0.02; // Adjust rotation speed as needed
    if (groupRef.current.rotation.y >= Math.Pi * 2) {
      groupRef.current.rotation.y = 0; // Reset rotation after a full 360°      
    }
    }
  });

  const revealContainer = {
    hidden: { opacity: 1 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1, // Delay between each child reveal
      },
    },
  };

  const revealVariant = {
    hidden: {
      opacity: 0,
      scale: 0.8, // Start small
      x: -100, // Start offscreen on the X-axis
      // y: 100, // Start offscreen on the Y-axis
    },
    visible: {
      opacity: 1,
      scale: 1, // Full size
      x: 0, // Centered on the X-axis
      // y: 0, // Centered on the Y-axis
      transition: {
        duration: 1, // Animation duration
        ease: "easeInOut", // Smooth easing
      },
    },
  };


  const { nodes, materials } = useGLTF('/building.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={2} decay={2} position={[4.21, 1.512, 0.09]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={2} decay={2} position={[4.21, 1.512, -1.064]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={2} decay={2} position={[2.168, 2.168, -4.781]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight
        intensity={10}
        decay={2}
        position={[2.823, 3.31, -2.863]}
        rotation={[-Math.PI / 2, 1.06, 0]}
      />
      <pointLight
        intensity={10}
        decay={2}
        position={[2.823, 3.287, -1.419]}
        rotation={[-Math.PI / 2, 1.06, 0]}
      />
      <pointLight
        intensity={10}
        decay={2}
        position={[2.823, 3.242, 0.041]}
        rotation={[-Math.PI / 2, 1.06, 0]}
      />
      <PerspectiveCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={28}
        position={[18.885, 6.176, -0.533]}
        rotation={[-1.674, 1.266, 1.679]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-0.775, 0.975, -7.088]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-4.974, 0.318, -3.367]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-4.974, 0.318, 0.239]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-4.974, 0.318, 3.496]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-1.581, 0.635, 7.893]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[3.05, 0.635, 7.893]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[5.223, 0.635, 3.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[5.223, 0.635, -0.722]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[5.223, 0.635, -3.44]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[5.223, 0.635, -5.453]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[2.105, -0.336, -5.363]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-0.437, 3.528, 2.55]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-0.437, 3.528, -1.367]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-1.046, 0.736, -0.292]}
        rotation={[-Math.PI / 2, 0, 0]}
      />

      <motion.group 
      variants={revealContainer}
      initial="hidden"
      animate="visible"
      ref={groupRef}>
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube001.geometry} material={materials.glow} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube003.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Plane.geometry} material={materials.glow} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder004.geometry} material={materials.metal} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube004.geometry} material={materials['Material.004']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder005.geometry} material={materials.metal} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder006.geometry} material={materials.metal} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder007.geometry} material={materials.metal} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.NurbsPath.geometry} material={materials['Material.001']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube005.geometry} material={materials['Material.001']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube006.geometry} material={materials.glow} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube008.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.NurbsPath001.geometry} material={materials.glow} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder008.geometry} material={materials['Material.001']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder009.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder010.geometry} material={materials.metal} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube011.geometry} material={materials['Material.004']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder011.geometry} material={materials.metal} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder012.geometry} material={materials.metal} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder013.geometry} material={materials.metal} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube009.geometry} material={materials['Material.001']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Plane001.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube014.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube015.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cylinder017.geometry} material={materials.glow} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube016.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube017.geometry} material={materials.Material} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube018.geometry} material={materials['Material.004']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube019.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Plane004.geometry} material={materials['Material.004']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Text.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Text001.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube020.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube021.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube022.geometry} material={materials.darkblue} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.thirdChair.geometry} material={materials.wood} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.thirdChair001.geometry} material={materials['Material.014']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.eb_house_plant_03.geometry} material={materials.blinn1SG} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.eb_house_plant_02.geometry} material={materials['blinn1SG.001']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube009_1.geometry} material={materials['Material.001']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Cube009_2.geometry} material={materials.logo} />
      <motion.mesh 
      initial={{
        scale: 0,
        opacity: 0,
      }}
      animate={{
        scale: 1,
        opacity: 1,
        transition: {delay: 1, duration: 1 },
      }}
      geometry={nodes.main.geometry} material={materials.darkblue} />
      <motion.mesh 
      initial={{
        scale: 0,
        opacity: 0,
      }}
      animate={{
        scale: 1,
        opacity: 1,
        transition: {delay: 1, duration: 1},
      }}
      geometry={nodes.main_1.geometry} material={materials['Material.001']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Wolf3D_Body003.geometry} material={materials['Wolf3D_Body.009']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Wolf3D_Body003_1.geometry} material={materials['Wolf3D_Eye.009']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Wolf3D_Body003_2.geometry} material={materials['Wolf3D_Skin.009']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Wolf3D_Body003_3.geometry} material={materials['Wolf3D_Teeth.009']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Wolf3D_Body003_4.geometry} material={materials.M_Hair_60} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Wolf3D_Body003_5.geometry} material={materials['Wolf3D_Outfit_Bottom.009']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Wolf3D_Body003_6.geometry} material={materials['Wolf3D_Outfit_Footwear.009']} />
      <motion.mesh 
      varients={revealVariant}
      initial="hidden"
      animate="visible"
      geometry={nodes.Wolf3D_Body003_7.geometry} material={materials['Wolf3D_Outfit_Top.009']} />
    </motion.group>
  </group>
  )
}

useGLTF.preload('/building.glb')
