/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 modern.glb 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Modern(props) {
  const { nodes, materials } = useGLTF('/modern.glb')
  return (
    <group {...props} dispose={null}>
      <pointLight intensity={10} decay={2} position={[2.823, 3.31, -2.863]} rotation={[-Math.PI / 2, 1.06, 0]} />
      <pointLight intensity={10} decay={2} position={[2.823, 3.287, -1.419]} rotation={[-Math.PI / 2, 1.06, 0]} />
      <pointLight intensity={10} decay={2} position={[2.823, 3.242, 0.041]} rotation={[-Math.PI / 2, 1.06, 0]} />
      <PerspectiveCamera makeDefault={true} far={1000} near={0.1} fov={22.895} position={[18.885, 6.176, -0.533]} rotation={[-1.674, 1.266, 1.679]} />
      <pointLight intensity={20} decay={2} position={[-0.775, 0.975, -7.088]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[-4.974, 0.318, -3.367]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[-4.974, 0.318, 0.239]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[-4.974, 0.318, 3.496]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[-1.581, 0.635, 7.893]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[3.05, 0.635, 7.893]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[5.223, 0.635, 3.3]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[5.223, 0.635, -0.722]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[5.223, 0.635, -3.44]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[5.223, 0.635, -5.453]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[2.105, -0.336, -5.363]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[-0.437, 3.528, 2.55]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[-0.437, 3.528, -1.367]} rotation={[-Math.PI / 2, 0, 0]} />
      <pointLight intensity={20} decay={2} position={[-1.046, 0.736, -0.292]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.glow} position={[0, -0.229, 0]} scale={[1.687, 1.215, 1.513]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0, -0.229, 0]} scale={[1.687, 1.215, 1.513]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials.darkblue} position={[-1.247, 0.419, -4.102]} scale={[0.106, 1.6, 0.106]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.darkblue} position={[-1.605, 0.445, 4.037]} rotation={[0, 0.003, 0]} scale={[1.236, 1.613, 1.267]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.glow} position={[-2.755, 0.406, -0.941]} rotation={[0, 0, -Math.PI / 2]} scale={1.452} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.metal} position={[0.471, 1.805, 5.144]} scale={[0.052, 0.161, 0.052]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.003']} position={[0.963, 0.713, 5.174]} rotation={[0, 0, -Math.PI]} scale={[-0.988, -1.12, -0.149]} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.metal} position={[1.165, 1.682, 5.144]} scale={[0.044, 0.294, 0.044]} />
      <mesh geometry={nodes.Cylinder006.geometry} material={materials.metal} position={[1.165, -0.752, 5.144]} scale={[0.055, 0.306, 0.055]} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.metal} position={[0.396, -0.726, 5.144]} scale={[0.057, 0.349, 0.057]} />
      <mesh geometry={nodes.NurbsPath.geometry} material={materials.Material} position={[2.286, -1.077, 2.636]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.325} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.Material} position={[2.225, -0.61, 0.375]} scale={[0.243, 0.375, 0.782]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.glow} position={[2.225, -0.61, 0.375]} scale={[0.243, 0.375, 0.782]} />
      <group position={[2.164, -0.581, -3.806]} scale={[0.142, 0.484, 1.149]}>
        <mesh geometry={nodes.Cube009_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cube009_2.geometry} material={materials.logo} />
      </group>
      <mesh geometry={nodes.Cube008.geometry} material={materials.darkblue} position={[2.164, -0.581, -3.806]} scale={[0.142, 0.484, 1.149]} />
      <mesh geometry={nodes.NurbsPath001.geometry} material={materials.glow} position={[2.286, -1.077, 2.636]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={1.325} />
      <mesh geometry={nodes.Cylinder008.geometry} material={materials.Material} position={[-0.092, -0.746, 0.63]} scale={[1.086, 0.41, 1.086]} />
      <mesh geometry={nodes.Cylinder009.geometry} material={materials.darkblue} position={[-0.092, -0.746, 0.63]} scale={[1.086, 0.41, 1.086]} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.metal} position={[-0.749, 1.117, -5.222]} scale={[0.04, 0.125, 0.04]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.005']} position={[-0.369, 0.274, -5.199]} rotation={[0, 0, -Math.PI]} scale={[-0.763, -0.866, -0.115]} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.metal} position={[-0.213, 1.321, -5.222]} scale={[0.034, 0.759, 0.034]} />
      <mesh geometry={nodes.Cylinder012.geometry} material={materials.metal} position={[-0.213, -0.859, -5.222]} scale={[0.042, 0.236, 0.042]} />
      <mesh geometry={nodes.Cylinder013.geometry} material={materials.metal} position={[-0.807, -0.838, -5.222]} scale={[0.044, 0.269, 0.044]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Material} position={[-2.042, -0.611, -2.755]} scale={[0.599, 0.347, 1.518]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.darkblue} position={[-1.972, 0.98, -5.297]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.Cylinder016.geometry} material={nodes.Cylinder016.material} position={[3.21, 3.573, -2.878]} rotation={[0, 0, -1.029]} scale={[0.245, 0.436, 0.245]} />
      <mesh geometry={nodes.Cube010.geometry} material={nodes.Cube010.material} position={[2.459, 3.382, -2.879]} scale={[0.601, 0.04, 0.04]} />
      <mesh geometry={nodes.Cylinder014.geometry} material={nodes.Cylinder014.material} position={[3.21, 3.573, -1.384]} rotation={[0, 0, -1.029]} scale={[0.245, 0.436, 0.245]} />
      <mesh geometry={nodes.Cube012.geometry} material={nodes.Cube012.material} position={[2.459, 3.382, -1.385]} scale={[0.601, 0.04, 0.04]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={nodes.Cylinder015.material} position={[3.21, 3.573, 0.038]} rotation={[0, 0, -1.029]} scale={[0.245, 0.436, 0.245]} />
      <mesh geometry={nodes.Cube013.geometry} material={nodes.Cube013.material} position={[2.459, 3.382, 0.037]} scale={[0.601, 0.04, 0.04]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.darkblue} position={[0, -0.229, 0]} scale={[1.687, 1.215, 1.513]} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.darkblue} position={[0, -0.229, 0]} scale={[1.687, 1.215, 1.513]} />
      <mesh geometry={nodes.Cylinder017.geometry} material={materials.glow} position={[-0.092, -0.746, 0.63]} scale={[1.086, 0.41, 1.086]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.darkblue} position={[0.963, 0.713, 5.174]} rotation={[0, 0, -Math.PI]} scale={[-0.988, -1.12, -0.149]} />
      <mesh geometry={nodes.Cube017.geometry} material={materials['Material.003']} position={[0.963, 0.713, 5.174]} rotation={[0, 0, -Math.PI]} scale={[-0.988, -1.12, -0.149]} />
      <mesh geometry={nodes.Cube018.geometry} material={materials['Material.004']} position={[-0.369, 0.274, -5.199]} rotation={[0, 0, -Math.PI]} scale={[-0.763, -0.866, -0.115]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials.darkblue} position={[-0.369, 0.274, -5.199]} rotation={[0, 0, -Math.PI]} scale={[-0.763, -0.866, -0.115]} />
      <group position={[-2.084, -1.004, -2.126]} scale={[0.861, 1, 3.366]}>
        <mesh geometry={nodes.main.geometry} material={materials.darkblue} />
        <mesh geometry={nodes.main_1.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Plane004.geometry} material={materials['Material.001']} position={[-2.755, 0.406, -0.941]} rotation={[0, 0, -Math.PI / 2]} scale={1.452} />
      <mesh geometry={nodes.Text.geometry} material={materials.darkblue} position={[1.778, 2.702, 0.977]} rotation={[Math.PI / 2, 0, -1.561]} scale={[0.725, 1.736, 0.725]} />
      <mesh geometry={nodes.Text001.geometry} material={materials.darkblue} position={[2.564, -0.477, 0.404]} rotation={[1.574, 0.318, -1.572]} scale={[0.157, 0.375, 0.157]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.002']} position={[-1.605, 0.445, 4.037]} rotation={[0, 0.003, 0]} scale={[1.236, 1.613, 1.267]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.002']} position={[-1.605, 0.445, 4.037]} rotation={[0, 0.003, 0]} scale={[1.236, 1.613, 1.267]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials.darkblue} position={[0, -0.229, 0]} scale={[1.687, 1.215, 1.513]} />
    </group>
  )
}

useGLTF.preload('/modern.glb')
