/*
Auto-generated by: https:githcom/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 modern.glb 
*/

import React, { useEffect, useRef, useState } from "react";
import { PerspectiveCamera, useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import { useFrame } from "@react-three/fiber";

export function Modern(props) {
  const groupRef = useRef();
  const [animate, setAnimate] = useState(false);
  useEffect(() => {
    setTimeout(() => {
      setAnimate(true);
    }, 6000);
    setTimeout(() => {
      setAnimate(false);
    }, 16500);
    
  }, [])
  useFrame(() => {
    if (animate === true) {
    groupRef.current.rotation.y += 0.02; // Adjust rotation speed as needed
    if (groupRef.current.rotation.y >= Math.Pi * 2) {
      groupRef.current.rotation.y = 0; // Reset rotation after a full 360°      
    }
    }
  });

  const revealContainer = {
    hidden: { opacity: 1 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1, // Delay between each child reveal
      },
    },
  };

  const revealVariant = {
    hidden: {
      opacity: 0,
      scale: 0.8, // Start small
      x: -100, // Start offscreen on the X-axis
      y: 100, // Start offscreen on the Y-axis
    },
    visible: {
      opacity: 1,
      scale: 1, // Full size
      x: 0, // Centered on the X-axis
      y: 0, // Centered on the Y-axis
      transition: {
        duration: 1, // Animation duration
        ease: "easeInOut", // Smooth easing
      },
    },
  };

  const { nodes, materials } = useGLTF("/modern.glb");
  return (
    <group {...props} dispose={null}>
      <pointLight
        intensity={10}
        decay={2}
        position={[2.823, 3.31, -2.863]}
        rotation={[-Math.PI / 2, 1.06, 0]}
      />
      <pointLight
        intensity={10}
        decay={2}
        position={[2.823, 3.287, -1.419]}
        rotation={[-Math.PI / 2, 1.06, 0]}
      />
      <pointLight
        intensity={10}
        decay={2}
        position={[2.823, 3.242, 0.041]}
        rotation={[-Math.PI / 2, 1.06, 0]}
      />
      <PerspectiveCamera
        makeDefault={true}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[18.885, 6.176, -0.533]}
        rotation={[-1.674, 1.266, 1.679]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-0.775, 0.975, -7.088]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-4.974, 0.318, -3.367]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-4.974, 0.318, 0.239]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-4.974, 0.318, 3.496]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-1.581, 0.635, 7.893]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[3.05, 0.635, 7.893]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[5.223, 0.635, 3.3]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[5.223, 0.635, -0.722]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[5.223, 0.635, -3.44]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[5.223, 0.635, -5.453]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[2.105, -0.336, -5.363]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-0.437, 3.528, 2.55]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-0.437, 3.528, -1.367]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={20}
        decay={2}
        position={[-1.046, 0.736, -0.292]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <motion.group
        ref={groupRef}
        variants={revealContainer}
        initial="hidden"
        animate="visible"
      >
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube001.geometry}
          material={materials.glow}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube003.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Plane.geometry}
          material={materials.glow}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder004.geometry}
          material={materials.metal}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube004.geometry}
          material={materials["Material.003"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder005.geometry}
          material={materials.metal}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder006.geometry}
          material={materials.metal}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder007.geometry}
          material={materials.metal}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.NurbsPath.geometry}
          material={materials["Material.001"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube005.geometry}
          material={materials["Material.001"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube006.geometry}
          material={materials.glow}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube008.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.NurbsPath001.geometry}
          material={materials.glow}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder008.geometry}
          material={materials["Material.001"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder009.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder010.geometry}
          material={materials.metal}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube011.geometry}
          material={materials["Material.005"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder011.geometry}
          material={materials.metal}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder012.geometry}
          material={materials.metal}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder013.geometry}
          material={materials.metal}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube009.geometry}
          material={materials["Material.001"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Plane001.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder016.geometry}
          material={nodes.Cylinder016.material}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder014.geometry}
          material={nodes.Cylinder014.material}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube012.geometry}
          material={nodes.Cube012.material}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder015.geometry}
          material={nodes.Cylinder015.material}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube013.geometry}
          material={nodes.Cube013.material}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube014.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube015.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cylinder017.geometry}
          material={materials.glow}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube016.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube017.geometry}
          material={materials["Material.003"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube018.geometry}
          material={materials["Material.004"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube019.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Plane004.geometry}
          material={materials["Material.002"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Text.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Text001.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube020.geometry}
          material={materials["Material.006"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube021.geometry}
          material={materials["Material.006"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube022.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube009_1.geometry}
          material={materials["Material.001"]}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.Cube009_2.geometry}
          material={materials.logo}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.main.geometry}
          material={materials.darkblue}
        />
        <motion.mesh
          variants={revealVariant}
          geometry={nodes.main_1.geometry}
          material={materials["Material.001"]}
        />
      </motion.group>
    </group>
  );
}

useGLTF.preload("/modern.glb");
